In [2]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in C:\Users\Kurly\anaconda3\envs\Final_Project\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Kurly\anaconda3\envs\Final_Project\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Kurly\anaconda3\envs\Final_Project\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Kurly\anaconda3\envs\Final_Project\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Kurly\anaconda3\envs\Final_Project\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in C:\Users\Kurly\anaconda3\envs\Final_Project\Lib\site-packages (2.4.2)

In [3]:
import pandas as pd
import numpy as np

In [4]:
customer_df = pd.read_csv("data/customer_dataset.csv")
inventory_df = pd.read_csv("data/inventory_dataset.csv")
suppliers_df = pd.read_csv("data/suppliers_dataset.csv")
invoice_df = pd.read_csv("data/invoices_10k.csv")

support_tickets_df = pd.read_csv("data/support_tickets.csv")
accounting_df = pd.read_csv("data/accounting_transactions.csv")

In [5]:
invoice_line_item_df = pd.read_csv("data/invoice_line_items.csv")

In [6]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          750 non-null    str
 1   name                 750 non-null    str
 2   email                750 non-null    str
 3   phone                750 non-null    str
 4   region               750 non-null    str
 5   industry             750 non-null    str
 6   customer_value_tier  750 non-null    str
 7   date_joined          750 non-null    str
dtypes: str(8)
memory usage: 47.0 KB

In [7]:
customer_df.head()

,customer_id,name,email,phone,region,industry,customer_value_tier,date_joined
0,CUST-2000,Patricia Garcia,patricia.garcia88@timbertools-example.com,(588) 555-7682,Southeast,Residential Construction,Gold,2025-01-15
1,CUST-2001,Sarah Johnson,sarah.johnson71@timbertools-example.com,(470) 555-1510,Southeast,Landscaping,Silver,2025-12-13
2,CUST-2002,William Jackson,william.jackson45@timbertools-example.com,(665) 555-9286,Midwest,Residential Construction,Silver,2025-12-06
3,CUST-2003,Charles Brown,charles.brown25@timbertools-example.com,(319) 555-8784,Midwest,Property Management,Silver,2023-08-19
4,CUST-2004,Patricia Garcia,patricia.garcia26@timbertools-example.com,(345) 555-6001,Southeast,Landscaping,Bronze,2025-04-05

In [8]:
customer_df.describe()

,customer_id,name,email,phone,region,industry,customer_value_tier,date_joined
count,750,750,750,750,750,750,750,750
unique,750,350,740,750,4,5,3,523
top,CUST-2000,James Garcia,robert.johnson72@timbertools-example.com,(588) 555-7682,Southeast,DIY / Individual,Bronze,2025-09-29
freq,1,6,2,1,287,300,431,4

In [9]:
customer_df.isnull().sum()

customer_id            0
name                   0
email                  0
phone                  0
region                 0
industry               0
customer_value_tier    0
date_joined            0
dtype: int64

In [10]:
customer_df.duplicated().sum()

np.int64(0)

In [11]:
customer_df.nunique()

customer_id            750
name                   350
email                  740
phone                  750
region                   4
industry                 5
customer_value_tier      3
date_joined            523
dtype: int64

In [12]:
#We want customer data to have unique name, email, and phone to simulate 750 diffrent customers. We will replace a database with unique value to exsisting database.
customer_unique_data_df = pd.read_csv("data/customer_unique_data.csv")
customer_unique_data_df.head()

   id                 name                         email
0   1           Cris Chark             cchark0@jimdo.com
1   2       Nara Blacksell         nblacksell1@adobe.com
2   3       Niles Kinchlea            nkinchlea2@ask.com
3   4       Jillayne Guile      jguile3@surveymonkey.com
4   5  Rosina Kindleysides  rkindleysides4@webeden.co.uk

In [13]:
customer_unique_data_df.info()
customer_unique_data_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      750 non-null    int64
 1   name    750 non-null    str
 2   email   750 non-null    str
dtypes: int64(1), str(2)
memory usage: 17.7 KB

              id
count  750.00000
mean   375.50000
std    216.65064
min      1.00000
25%    188.25000
50%    375.50000
75%    562.75000
max    750.00000

In [14]:
customer_unique_data_df.isnull().sum()

id       0
name     0
email    0
dtype: int64

In [15]:
customer_unique_data_df.duplicated().sum()

np.int64(0)

In [16]:
customer_unique_data_df.nunique()

id       750
name     750
email    750
dtype: int64

In [17]:
customer_df['name'] = customer_unique_data_df['name'].values
customer_df['email'] = customer_unique_data_df['email'].values

In [18]:
customer_df.head()

,customer_id,name,email,phone,region,industry,customer_value_tier,date_joined
0,CUST-2000,Cris Chark,cchark0@jimdo.com,(588) 555-7682,Southeast,Residential Construction,Gold,2025-01-15
1,CUST-2001,Nara Blacksell,nblacksell1@adobe.com,(470) 555-1510,Southeast,Landscaping,Silver,2025-12-13
2,CUST-2002,Niles Kinchlea,nkinchlea2@ask.com,(665) 555-9286,Midwest,Residential Construction,Silver,2025-12-06
3,CUST-2003,Jillayne Guile,jguile3@surveymonkey.com,(319) 555-8784,Midwest,Property Management,Silver,2023-08-19
4,CUST-2004,Rosina Kindleysides,rkindleysides4@webeden.co.uk,(345) 555-6001,Southeast,Landscaping,Bronze,2025-04-05

In [19]:
customer_df.nunique()

customer_id            750
name                   750
email                  750
phone                  750
region                   4
industry                 5
customer_value_tier      3
date_joined            523
dtype: int64

In [22]:
customer_df.to_csv("data/customer__modified_dataset.csv", index=False)

In [23]:
inventory_df.info()
inventory_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          300 non-null    str
 1   product_name        300 non-null    str
 2   category            300 non-null    str
 3   supplier_id         300 non-null    str
 4   unit_cost           300 non-null    float64
 5   current_stock       300 non-null    int64
 6   reorder_level       300 non-null    int64
 7   reorder_quantity    300 non-null    int64
 8   warehouse_location  300 non-null    str
 9   unit_price          300 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 23.6 KB

        unit_cost  current_stock  reorder_level  reorder_quantity  unit_price
count  300.000000     300.000000     300.000000        300.000000   300.00000
mean    98.270000     108.496667      37.610000         75.220000   145.63650
std    116.533395      47.574936      13.863328         27.726657   163.25348
min      3.000000       1.000000      15.000000         30.000000     7.50000
25%     22.000000      73.000000      25.750000         51.500000    36.50000
50%     55.000000     107.000000      38.000000         76.000000    84.00000
75%    145.000000     144.250000      50.250000        100.500000   219.00000
max    650.000000     214.000000      60.000000        120.000000   899.00000

In [24]:
inventory_df.isnull().sum()

product_id            0
product_name          0
category              0
supplier_id           0
unit_cost             0
current_stock         0
reorder_level         0
reorder_quantity      0
warehouse_location    0
unit_price            0
dtype: int64

In [25]:
inventory_df.duplicated().sum()

np.int64(0)

In [26]:
inventory_df.nunique()

product_id            300
product_name          292
category                5
supplier_id            12
unit_cost              24
current_stock         147
reorder_level          46
reorder_quantity       46
warehouse_location      8
unit_price             25
dtype: int64

In [27]:
inventory_df.tail()

,product_id,product_name,category,supplier_id,unit_cost,current_stock,reorder_level,reorder_quantity,warehouse_location,unit_price
295,PROD-6295,Ridgid 18V Brushless Recip Saw (Mod-295),Power Tools,SUPP-04,90.0,43,23,46,No-WH1,139.00
296,PROD-6296,Tiki Brand Bamboo Torch (Mod-296),Garden & Outdoor,SUPP-07,6.0,140,20,40,No-WH1,12.50
297,PROD-6297,Stanley FatMax 25ft Tape Measure (Mod-297),Hardware,SUPP-09,14.0,141,55,110,We-WH2,24.97
298,PROD-6298,3/4in x 4ft x 8ft Oak Plywood (Mod-298),Lumber,SUPP-11,55.0,161,54,108,Mi-WH2,84.00
299,PROD-6299,Kohler Forte Kitchen Faucet (Mod-299),Plumbing,SUPP-15,145.0,125,57,114,No-WH1,219.00

In [28]:
#We want product names to distinct meanigful name. As you can see in the tail, the database just adds "mod" to try to create unique names. We will have to fix this also.
inventory_unique_data_df = pd.read_csv("data/inventory_unique.csv")
inventory_unique_data_df.head()

,product_id,product_name,category,unit_price
0,1001,Craftsman 20V MAX Cordless Drill Kit,Power Tools,99.0
1,1002,DeWalt 20V MAX Brushless Impact Driver,Power Tools,129.0
2,1003,Makita 18V LXT Lithium-Ion Cordless Drill,Power Tools,119.0
3,1004,Milwaukee M18 18V Cordless 1/2 in. Drill Driver,Power Tools,139.0
4,1005,Ryobi ONE+ 18V Cordless Drill/Driver,Power Tools,79.0

In [29]:
inventory_unique_data_df.info()
inventory_unique_data_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    300 non-null    int64
 1   product_name  300 non-null    str
 2   category      300 non-null    str
 3   unit_price    300 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 9.5 KB

        product_id  unit_price
count   300.000000  300.000000
mean   1150.500000   53.840767
std      86.746758   87.925307
min    1001.000000    0.480000
25%    1075.750000    6.980000
50%    1150.500000   16.980000
75%    1225.250000   59.000000
max    1300.000000  599.000000

In [30]:
inventory_unique_data_df.isnull().sum()

product_id      0
product_name    0
category        0
unit_price      0
dtype: int64

In [31]:
inventory_unique_data_df.duplicated().sum()

np.int64(0)

In [32]:
inventory_unique_data_df.nunique()

product_id      300
product_name    300
category          5
unit_price       80
dtype: int64

In [33]:
inventory_df['product_name'] = inventory_unique_data_df['product_name'].values
inventory_df['category'] = inventory_unique_data_df['category'].values
inventory_df['unit_price'] = inventory_unique_data_df['unit_price'].values

In [34]:
inventory_df.nunique()

product_id            300
product_name          300
category                5
supplier_id            12
unit_cost              24
current_stock         147
reorder_level          46
reorder_quantity       46
warehouse_location      8
unit_price             80
dtype: int64

In [36]:
inventory_df.to_csv("data/inventory__modified_dataset.csv", index=False)

In [37]:
#Because we changed unit_price we know need to make sure unit_cost is below that. We will give random profit margin of 25-40 with the average being closer to 35%
inventory_df['unit_cost'] = (inventory_df['unit_price'] / (1 + np.random.uniform(0.25, 0.40, size=len(inventory_df)))).round(2)

In [38]:
inventory_df.describe()

        unit_cost  current_stock  reorder_level  reorder_quantity  unit_price
count  300.000000     300.000000     300.000000        300.000000  300.000000
mean    40.683133     108.496667      37.610000         75.220000   53.840767
std     66.976328      47.574936      13.863328         27.726657   87.925307
min      0.350000       1.000000      15.000000         30.000000    0.480000
25%      4.997500      73.000000      25.750000         51.500000    6.980000
50%     12.420000     107.000000      38.000000         76.000000   16.980000
75%     43.930000     144.250000      50.250000        100.500000   59.000000
max    469.320000     214.000000      60.000000        120.000000  599.000000

In [39]:
inventory_df.to_csv("data/inventory__modified_dataset.csv", index=False)

In [41]:
inventory_df.head()

,product_id,product_name,category,supplier_id,unit_cost,current_stock,reorder_level,reorder_quantity,warehouse_location,unit_price
0,PROD-6000,Craftsman 20V MAX Cordless Drill Kit,Power Tools,SUPP-01,72.76,7,36,72,We-WH1,99.0
1,PROD-6001,DeWalt 20V MAX Brushless Impact Driver,Power Tools,SUPP-05,92.37,7,35,70,No-WH2,129.0
2,PROD-6002,Makita 18V LXT Lithium-Ion Cordless Drill,Power Tools,SUPP-08,91.10,1,58,116,So-WH1,119.0
3,PROD-6003,Milwaukee M18 18V Cordless 1/2 in. Drill Driver,Power Tools,SUPP-11,106.07,53,58,116,No-WH2,139.0
4,PROD-6004,Ryobi ONE+ 18V Cordless Drill/Driver,Power Tools,SUPP-15,61.95,6,29,58,So-WH2,79.0

In [42]:
suppliers_df.head()

,supplier_id,supplier_name,contact_email,lead_time_days,rating,payment_terms
0,SUPP-01,DeWalt Tools Inc.,sales@dewalt-dist.com,7,4.8,Net-30
1,SUPP-02,Milwaukee Tool Corp,orders@milwaukee.com,10,4.7,Net-30
2,SUPP-03,Makita USA,support@makita-wholesale.com,22,3.2,Net-60
3,SUPP-04,Bosch Power Systems,b2b@bosch.com,14,4.5,Net-30
4,SUPP-05,EGO Power+,fulfillment@egopower.com,12,4.9,Net-15

In [43]:
suppliers_df.info()
suppliers_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   supplier_id     20 non-null     str
 1   supplier_name   20 non-null     str
 2   contact_email   20 non-null     str
 3   lead_time_days  20 non-null     int64
 4   rating          20 non-null     float64
 5   payment_terms   20 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 1.1 KB

       lead_time_days     rating
count       20.000000  20.000000
mean        12.600000   4.420000
std         10.850176   0.537636
min          3.000000   2.800000
25%          5.000000   4.375000
50%          8.500000   4.550000
75%         15.000000   4.725000
max         40.000000   4.900000

In [44]:
suppliers_df.isnull().sum()

supplier_id       0
supplier_name     0
contact_email     0
lead_time_days    0
rating            0
payment_terms     0
dtype: int64

In [25]:
suppliers_df.duplicated().sum()

np.int64(0)

In [26]:
suppliers_df.nunique()

supplier_id       20
supplier_name     20
contact_email     20
lead_time_days    13
rating            11
payment_terms      4
dtype: int64

In [45]:
invoice_df.head()

,invoice_id,customer_id,invoice_date,due_date,payment_status,subtotal,tax_amount,total_amount,payment_method,sales_rep,region
0,INV-50000,CUST-2043,2025-10-18,2025-11-17,Paid,1604.73,120.35,1725.08,Debit Card,J. Miller,Northeast
1,INV-50001,CUST-2172,2025-02-01,2025-03-03,Paid,410.03,30.75,440.78,Debit Card,K. Tanaka,Midwest
2,INV-50002,CUST-2670,2025-02-13,2025-03-15,Overdue,717.50,53.81,771.31,Credit Card,A. Vance,Midwest
3,INV-50003,CUST-2362,2024-11-04,2024-12-04,Paid,1888.72,141.65,2030.37,Store Credit,K. Tanaka,Northeast
4,INV-50004,CUST-2357,2025-08-15,2025-09-14,Paid,2201.50,165.11,2366.61,ACH Transfer,A. Vance,West

In [46]:
invoice_df.info()
invoice_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10000 non-null  str
 1   customer_id     10000 non-null  str
 2   invoice_date    10000 non-null  str
 3   due_date        10000 non-null  str
 4   payment_status  10000 non-null  str
 5   subtotal        10000 non-null  float64
 6   tax_amount      10000 non-null  float64
 7   total_amount    10000 non-null  float64
 8   payment_method  10000 non-null  str
 9   sales_rep       10000 non-null  str
 10  region          10000 non-null  str
dtypes: float64(3), str(8)
memory usage: 859.5 KB

           subtotal    tax_amount  total_amount
count  10000.000000  10000.000000  10000.000000
mean    2276.923077    170.769199   2447.692276
std     1297.823213     97.336727   1395.159941
min       25.080000      1.880000     26.960000
25%     1142.955000     85.725000   1228.680000
50%     2291.235000    171.845000   2463.080000
75%     3407.037500    255.530000   3662.567500
max     4499.800000    337.490000   4837.290000

In [47]:
invoice_df.isnull().sum()

invoice_id        0
customer_id       0
invoice_date      0
due_date          0
payment_status    0
subtotal          0
tax_amount        0
total_amount      0
payment_method    0
sales_rep         0
region            0
dtype: int64

In [48]:
invoice_df.duplicated().sum()

np.int64(0)

In [49]:
invoice_df.nunique()

invoice_id        10000
customer_id         750
invoice_date       1001
due_date           1001
payment_status        2
subtotal           9886
tax_amount         8616
total_amount       9886
payment_method        5
sales_rep             5
region                4
dtype: int64

In [50]:
invoice_line_item_df.head()

,line_item_id,invoice_id,product_id,quantity,unit_price,discount,total_amount
0,1,INV-50000,PROD-6174,323,4.98,0.0,1604.73
1,2,INV-50001,PROD-6114,2,249.00,0.0,351.07
2,3,INV-50001,PROD-6026,1,49.00,0.0,49.00
3,4,INV-50001,PROD-6232,1,5.98,0.0,5.98
4,5,INV-50001,PROD-6164,1,3.98,0.0,3.98

In [51]:
invoice_line_item_df.info()
invoice_line_item_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 30108 entries, 0 to 30107
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   line_item_id  30108 non-null  int64
 1   invoice_id    30108 non-null  str
 2   product_id    30108 non-null  str
 3   quantity      30108 non-null  int64
 4   unit_price    30108 non-null  float64
 5   discount      30108 non-null  float64
 6   total_amount  30108 non-null  float64
dtypes: float64(3), int64(2), str(2)
memory usage: 1.6 MB

       line_item_id      quantity    unit_price  discount  total_amount
count  30108.000000  30108.000000  30108.000000   30108.0  30108.000000
mean   15054.500000     58.486449     52.139722       0.0    756.251852
std     8691.575289    258.531926     89.766895       0.0    967.666237
min        1.000000      1.000000      0.480000       0.0   -126.610000
25%     7527.750000      6.000000      5.980000       0.0     77.740000
50%    15054.500000     15.000000     14.980000       0.0    319.680000
75%    22581.250000     39.000000     49.980000       0.0   1077.305000
max    30108.000000   8973.000000    599.000000       0.0   4498.710000

In [52]:
invoice_line_item_df.isnull().sum()

line_item_id    0
invoice_id      0
product_id      0
quantity        0
unit_price      0
discount        0
total_amount    0
dtype: int64

In [53]:
invoice_line_item_df.duplicated().sum()

np.int64(0)

In [54]:
invoice_line_item_df.nunique()

line_item_id    30108
invoice_id      10000
product_id        300
quantity          853
unit_price         80
discount            1
total_amount    13884
dtype: int64

In [56]:
#7 items are seem to be negatice. We will keep these discrepencys as it will act as noise or simulate human error. We might be able to see if AI catch these issues. We could also consider this as offering free or dicount products to the customer. We will see. 
lowest_ten = invoice_line_item_df.nsmallest(10, "total_amount") 
print(lowest_ten)

       line_item_id invoice_id product_id  quantity  unit_price  discount  \
5699           5700  INV-51902  PROD-6151         1        1.28       0.0
475             476  INV-50173  PROD-6017         1      149.00       0.0
2422           2423  INV-50819  PROD-6247         1        0.68       0.0
1306           1307  INV-50449  PROD-6155         1       14.98       0.0
28779         28780  INV-59550  PROD-6234         1       43.98       0.0
16424         16425  INV-55469  PROD-6098         1      199.00       0.0
21199         21200  INV-57035  PROD-6035         1      139.00       0.0
108             109  INV-50038  PROD-6103         1      249.00       0.0
119             120  INV-50043  PROD-6013         1      499.00       0.0
179             180  INV-50064  PROD-6006         1      149.00       0.0

       total_amount
5699        -126.61
475          -91.70
2422         -23.82
1306          -8.05
28779         -6.36
16424         -5.06
21199         -2.39
108            0.00
119            0.00
179            0.00

In [57]:
# we will delete discount as there is no discounts values
invoice_line_item_df = invoice_line_item_df.drop(columns=["discount"])

In [58]:
invoice_line_item_df.to_csv("data/invoice_line_item_modified.csv", index=False)

In [59]:
invoice_line_item_df.head()

   line_item_id invoice_id product_id  quantity  unit_price  total_amount
0             1  INV-50000  PROD-6174       323        4.98       1604.73
1             2  INV-50001  PROD-6114         2      249.00        351.07
2             3  INV-50001  PROD-6026         1       49.00         49.00
3             4  INV-50001  PROD-6232         1        5.98          5.98
4             5  INV-50001  PROD-6164         1        3.98          3.98

In [60]:
support_tickets_df.head()

,ticket_id,customer_id,date_opened,date_closed,status,priority,category,assigned_agent,resolution_time_hours,customer_sentiment,ticket_description,product_id,transaction_id
0,TIC-80000,CUST-2470,2024-01-28 00:00,2024-01-28 17:38,Closed,Medium,General Question,Agent_Smith,17.64,Neutral,General inquiry regarding order status or prod...,PROD-6024,INV-58518
1,TIC-80001,CUST-2370,2025-05-11 00:00,2025-05-11 12:01,Closed,Low,Technical Issue,Agent_Patel,12.02,Frustrated,EGO Power+ Mower fails to start or battery not...,PROD-6015,INV-57772
2,TIC-80002,CUST-2145,2025-06-02 00:00,2025-06-05 21:21,Closed,High,General Question,Agent_Lee,93.36,Negative,General inquiry regarding order status or prod...,PROD-6166,INV-53340
3,TIC-80003,CUST-2060,2025-12-20 00:00,2025-12-20 17:04,Closed,Low,Shipping Complaint,Agent_Patel,17.08,Negative,Package delayed due to holiday volume or damag...,PROD-6008,INV-54054
4,TIC-80004,CUST-2495,2024-04-22 00:00,NaN,Resolved,Medium,General Question,Agent_Smith,17.40,Negative,General inquiry regarding order status or prod...,PROD-6198,INV-55061

In [61]:
support_tickets_df.info()
support_tickets_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_id              2000 non-null   str
 1   customer_id            2000 non-null   str
 2   date_opened            2000 non-null   str
 3   date_closed            1401 non-null   str
 4   status                 2000 non-null   str
 5   priority               2000 non-null   str
 6   category               2000 non-null   str
 7   assigned_agent         2000 non-null   str
 8   resolution_time_hours  2000 non-null   float64
 9   customer_sentiment     2000 non-null   str
 10  ticket_description     2000 non-null   str
 11  product_id             2000 non-null   str
 12  transaction_id         2000 non-null   str
dtypes: float64(1), str(12)
memory usage: 203.3 KB

       resolution_time_hours
count            2000.000000
mean               27.119065
std                30.393568
min                 2.020000
25%                 8.737500
50%                15.605000
75%                22.562500
max               119.900000

In [62]:
support_tickets_df.isnull().sum()

ticket_id                  0
customer_id                0
date_opened                0
date_closed              599
status                     0
priority                   0
category                   0
assigned_agent             0
resolution_time_hours      0
customer_sentiment         0
ticket_description         0
product_id                 0
transaction_id             0
dtype: int64

In [63]:
support_tickets_df.duplicated().sum()

np.int64(0)

In [64]:
support_tickets_df.nunique()

ticket_id                2000
customer_id               703
date_opened               610
date_closed              1400
status                      5
priority                    4
category                    5
assigned_agent              5
resolution_time_hours    1521
customer_sentiment          4
ticket_description          3
product_id                280
transaction_id           1818
dtype: int64

In [73]:
#we will change the column name of transaction_id to invoice_id to match better
support_tickets_df = support_tickets_df.rename(columns={"transaction_id": "invoice_id"})
support_tickets_df.to_csv("data/support_ticket_modified.csv", index=False)

In [92]:
#We will also remove product_id as it makes no sence in thsi context
support_tickets_df = support_tickets_df.drop(columns=["product_id"])
support_tickets_df.to_csv("data/support_ticket_modified.csv", index=False)

In [93]:
support_tickets_df.head()

,ticket_id,customer_id,date_opened,date_closed,status,priority,category,assigned_agent,resolution_time_hours,customer_sentiment,ticket_description,invoice_id
0,TIC-80000,CUST-2470,2024-01-28 00:00,2024-01-28 17:38,Closed,Medium,General Question,Agent_Smith,17.64,Neutral,General inquiry regarding order status or prod...,INV-58518
1,TIC-80001,CUST-2370,2025-05-11 00:00,2025-05-11 12:01,Closed,Low,Technical Issue,Agent_Patel,12.02,Frustrated,EGO Power+ Mower fails to start or battery not...,INV-57772
2,TIC-80002,CUST-2145,2025-06-02 00:00,2025-06-05 21:21,Closed,High,General Question,Agent_Lee,93.36,Negative,General inquiry regarding order status or prod...,INV-53340
3,TIC-80003,CUST-2060,2025-12-20 00:00,2025-12-20 17:04,Closed,Low,Shipping Complaint,Agent_Patel,17.08,Negative,Package delayed due to holiday volume or damag...,INV-54054
4,TIC-80004,CUST-2495,2024-04-22 00:00,NaN,Resolved,Medium,General Question,Agent_Smith,17.40,Negative,General inquiry regarding order status or prod...,INV-55061

In [65]:
accounting_df.head()

,invoice_acct_id,date,account,description,amount,type,department,vendor,payment_method
0,ACT-10000,2023-01-01,Rent Expense,Monthly Store Lease,12000.00,Debit,Operations,RealEstate Holdings,ACH
1,ACT-10001,2023-01-15,Payroll,Employee Wages,49986.73,Debit,Admin,ADP Services,ACH
2,ACT-10002,2023-01-28,Payroll,Employee Wages,51772.03,Debit,Admin,ADP Services,ACH
3,ACT-10003,2023-02-01,Rent Expense,Monthly Store Lease,12000.00,Debit,Operations,RealEstate Holdings,ACH
4,ACT-10004,2023-02-15,Payroll,Employee Wages,47480.45,Debit,Admin,ADP Services,ACH

In [66]:
accounting_df.info()
accounting_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   invoice_acct_id  8500 non-null   str
 1   date             8500 non-null   str
 2   account          8500 non-null   str
 3   description      8500 non-null   str
 4   amount           8500 non-null   float64
 5   type             8500 non-null   str
 6   department       8500 non-null   str
 7   vendor           8500 non-null   str
 8   payment_method   8500 non-null   str
dtypes: float64(1), str(8)
memory usage: 597.8 KB

             amount
count   8500.000000
mean    8811.263972
std     7652.189825
min      100.210000
25%     3445.660000
50%     6376.830000
75%    12920.897500
max    51945.910000

In [67]:
accounting_df.isnull().sum()

invoice_acct_id    0
date               0
account            0
description        0
amount             0
type               0
department         0
vendor             0
payment_method     0
dtype: int64

In [68]:
accounting_df.duplicated().sum()

np.int64(0)

In [69]:
accounting_df.nunique()

invoice_acct_id    8500
date               1096
account               7
description           7
amount             8367
type                  2
department            5
vendor                7
payment_method        3
dtype: int64

In [80]:
print(accounting_df["amount"].sum().round(2))

74895743.76

In [81]:
print(invoice_line_item_df["total_amount"].sum().round(2))

22769230.77

In [82]:
print(invoice_df["total_amount"].sum().round(2))

24476922.76

In [88]:
#We can see that accouting cost are way more than the revenue from invoices. Since this company has been opating for 3 years lets assume they are profitable over all. We will lower the price of each item to make the amount more believable.
acccounting_modified_df = pd.read_csv("data/accounting_transactions.csv")
acccounting_modified_df["amount"] = (acccounting_modified_df["amount"] / 4).round(2)
print(acccounting_modified_df["amount"].sum().round(2))

18723936.23

In [89]:
24476922.76-18723936.23

5752986.530000001

In [90]:
acccounting_modified_df.to_csv("data/accounting_transactions_modified.csv", index=False)

In [91]:
acccounting_modified_df.head()

,invoice_acct_id,date,account,description,amount,type,department,vendor,payment_method
0,ACT-10000,2023-01-01,Rent Expense,Monthly Store Lease,3000.00,Debit,Operations,RealEstate Holdings,ACH
1,ACT-10001,2023-01-15,Payroll,Employee Wages,12496.68,Debit,Admin,ADP Services,ACH
2,ACT-10002,2023-01-28,Payroll,Employee Wages,12943.01,Debit,Admin,ADP Services,ACH
3,ACT-10003,2023-02-01,Rent Expense,Monthly Store Lease,3000.00,Debit,Operations,RealEstate Holdings,ACH
4,ACT-10004,2023-02-15,Payroll,Employee Wages,11870.11,Debit,Admin,ADP Services,ACH

In [95]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          750 non-null    str
 1   name                 750 non-null    str
 2   email                750 non-null    str
 3   phone                750 non-null    str
 4   region               750 non-null    str
 5   industry             750 non-null    str
 6   customer_value_tier  750 non-null    str
 7   date_joined          750 non-null    str
dtypes: str(8)
memory usage: 47.0 KB

In [96]:
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          300 non-null    str
 1   product_name        300 non-null    str
 2   category            300 non-null    str
 3   supplier_id         300 non-null    str
 4   unit_cost           300 non-null    float64
 5   current_stock       300 non-null    int64
 6   reorder_level       300 non-null    int64
 7   reorder_quantity    300 non-null    int64
 8   warehouse_location  300 non-null    str
 9   unit_price          300 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 23.6 KB

In [97]:
suppliers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   supplier_id     20 non-null     str
 1   supplier_name   20 non-null     str
 2   contact_email   20 non-null     str
 3   lead_time_days  20 non-null     int64
 4   rating          20 non-null     float64
 5   payment_terms   20 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 1.1 KB

In [98]:
invoice_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10000 non-null  str
 1   customer_id     10000 non-null  str
 2   invoice_date    10000 non-null  str
 3   due_date        10000 non-null  str
 4   payment_status  10000 non-null  str
 5   subtotal        10000 non-null  float64
 6   tax_amount      10000 non-null  float64
 7   total_amount    10000 non-null  float64
 8   payment_method  10000 non-null  str
 9   sales_rep       10000 non-null  str
 10  region          10000 non-null  str
dtypes: float64(3), str(8)
memory usage: 859.5 KB

In [99]:
invoice_line_item_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30108 entries, 0 to 30107
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   line_item_id  30108 non-null  int64
 1   invoice_id    30108 non-null  str
 2   product_id    30108 non-null  str
 3   quantity      30108 non-null  int64
 4   unit_price    30108 non-null  float64
 5   total_amount  30108 non-null  float64
dtypes: float64(2), int64(2), str(2)
memory usage: 1.4 MB

In [100]:
support_tickets_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_id              2000 non-null   str
 1   customer_id            2000 non-null   str
 2   date_opened            2000 non-null   str
 3   date_closed            1401 non-null   str
 4   status                 2000 non-null   str
 5   priority               2000 non-null   str
 6   category               2000 non-null   str
 7   assigned_agent         2000 non-null   str
 8   resolution_time_hours  2000 non-null   float64
 9   customer_sentiment     2000 non-null   str
 10  ticket_description     2000 non-null   str
 11  invoice_id             2000 non-null   str
dtypes: float64(1), str(11)
memory usage: 187.6 KB

In [101]:
acccounting_modified_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   invoice_acct_id  8500 non-null   str
 1   date             8500 non-null   str
 2   account          8500 non-null   str
 3   description      8500 non-null   str
 4   amount           8500 non-null   float64
 5   type             8500 non-null   str
 6   department       8500 non-null   str
 7   vendor           8500 non-null   str
 8   payment_method   8500 non-null   str
dtypes: float64(1), str(8)
memory usage: 597.8 KB